config/routes.rb
Foodiewall::Application.routes.draw do

  root 'foodiepictures#index'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  resources :foodiepictures
  resources :users
  resource  :session, only: [:new, :create, :destroy]
  resource :comment, only: [:create]

  get "users/error" => "users#error"

  get "user/name"
  get "user/password_digest"
  get "user/is_active"

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :comment, type: String

  belongs_to :user
  belongs_to :foodiepicture
end

app/models/foodiepicture.rb
class Foodiepicture
  include Mongoid::Document
  include Mongoid::Paperclip 
  field :description, type: String
  attr_accessor :user
  #field :picture_url, type: String

  belongs_to :user
  has_many :comments

  has_mongoid_attached_file :image
  # ,styles: {
  #   thumb: '100x100>',
  #   square: '200x200#',
  #   medium: '300x300>'
  # }
  validates_attachment_content_type :image, content_type:["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Paperclip 
  include ActiveModel::SecurePassword
  field :name, type: String
  field :password_digest, type: String
  field :is_active, type: Mongoid::Boolean, default: true

  # validates :name, presence: {message: "you need an username!"},
  #  uniqueness: {message: "think of something unique!"},
  #  length: { in 4..11 }
  #  format: { with: /\A[a-zA-Z]+\z/, message: "letters only!" }
  # validates :password, presence: {message: "you need a password!"},
  #  length: { in 4..11 }
  # validates :image, presence: {message: "you need an avatar!"}

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_confirmation_of :password
  validates_presence_of :password
  validates_length_of :name, minimum: 4, maximum: 11
  validates_length_of :password, minimum: 4, maximum: 11
  validates_presence_of :image

  has_secure_password

  has_many :foodiepictures
  has_many :comments

  has_mongoid_attached_file :image
  validates_attachment_content_type :image, content_type:["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

		puts "***********"

		# when on a particular photo page
		if params[:foodie_id]

			# find the particular photo
			@foodiepicture = Foodiepicture.find(params[:foodie_id])

			# attach new comment for this photo
			@comment_on_pic = @foodiepicture.comments.new(params.require(:comment).permit(:comment))
			# also attach comment to the current user
			@comment_on_pic.user_id = current_user.id

			if @comment_on_pic.save
				redirect_to foodiepicture_path(@foodiepicture.id)
			end

		# when on a particular user's wall
		else params[:userwall_id]

			# find the particular user's wall (user_id on the address)
			@user = User.find(params[:userwall_id])

			# attach new comment to the particular user wall
			@comment_on_user = @user.comments.new(params.require(:comment).permit(:comment))
			# also attach comment to the current user
			# @comment_on_user.user_id = @current_user.id

			if @comment_on_user.save
				redirect_to user_path(@user.id)
			end
		end
	end

end

app/controllers/concerns/sessions_controller.rb
class SessionsController < ApplicationController

  

  def create
  	u = User.where(name: params[:user][:name]).first
  	if u && u.authenticate(params[:user][:password])
  		if u.is_active == false
  			redirect_to reactivate_user_path(u.id)
  		else
  			session[:user_id] = u.id.to_s
        session[:name] = u.name.to_s
        session[:image] = u.image
  			redirect_to foodiepictures_path
  		end
  	else
  		redirect_to foodiepictures_path
  	end
  end

  def destroy
  	reset_session
  	redirect_to foodiepictures_path
  end
end

app/controllers/foodiepictures_controller.rb
class FoodiepicturesController < ApplicationController
	before_action :login, :signup, :comment_post

	def index
		@foodiepictures = Foodiepicture.all
		@form_type = params[:form_type]

	end

	def show
		if current_user
		@foodiepicture = Foodiepicture.find(params[:id])
		@id = params[:id]
	    else
	       redirect_to foodiepictures_path
	    end
	end

	def new
		if !current_user
			redirect_to foodiepictures_path
			return
		end
		@foodiepicture = Foodiepicture.new
	end

	def create
		if !current_user
			redirect_to foodiepictures_path
			return
		end
		foodiepicture = current_user.foodiepictures.new( params.require(:foodiepicture).permit(:image, :description) )
		if foodiepicture.save
			redirect_to foodiepictures_path
		end
	end

	def login
	  	@user_login = User.new
	  	@is_login = true
  	end

  	def signup
  	    @user = User.new
    end

    def comment_post
    	@comment_post = Comment.new
    end

	def edit
		@foodiepicture = Foodiepicture.find(params[:id])
		if (!current_user) || (@foodiepicture.user != current_user)
			redirect_to user_path(current_user)
			return
		end
	end

	def update
		@foodiepicture = Foodiepicture.find(params[:id])
		if (!current_user) || (@foodiepicture.user != current_user)
			redirect_to foodiepictures_path
			return
		elsif (@foodiepicture.user == current_user)
			if @foodiepicture.update_attributes(params.require(:foodiepicture).permit(:image, :description) )
				redirect_to user_path(current_user)
			else
				render 'edit'
			end
		else
			redirect_to foodiepictures_path
		end
	end

	def destroy
		@foodiepicture = Foodiepicture.find(params[:id])
		if (@foodiepicture.user == current_user)
			@foodiepicture.destroy
		 	redirect_to user_path(current_user)
		else
		 	redirect_to foodiepictures_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login, :comment_post
  # def index
  # 	@user = User.where(is_active: true)
  # end



  def create
  	@user = User.new(params.require(:user).permit(:name, :password, :password_confirmation, :image))
    @foodiepictures = Foodiepicture.all
    respond_to do |format|

        

      if @user.save

            session[:user_id] = @user.id.to_s
            format.html { redirect_to foodiepictures_path }

      else
        
        format.html { redirect_to foodiepictures_path, notice: @user.errors.full_messages.to_a.first }
      end
    end
  end

  def show
  	@user = User.find(params[:id])
    @foodiepictures = @user.foodiepictures
  end

  def comment_post
    @comment_post = Comment.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params:id)
  	if current_user != @user
  		if current_user
  			redirect_to user_path(current_user)
  		else
  			redirect_to new_path
  		end
  	elsif 
  		@user.update_attributes(params.require(:user).permit(:name, :password, :is_active))
  		redirect_to user_show_path
  	else
  		render :edit
  	end
  end

  def destroy
  	User.find(params[:id])
  	@user.is_active = false
  	@user.save
  	redirect_to users_path
  end

  def login
    @user_login = User.new
    @is_login = true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foodiepictures_helper.rb
module FoodiepicturesHelper
end

app/helpers/seesions_helper.rb
module SeesionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foodiepictures/edit.html.erb
<div class="newpic">
<h1>What do you wanna edit?</h1>
<%= form_for @foodiepicture do |f| %>
  <form class="form-horizontal" role="form">
	  <div class="form-group btn-pink">
	    <div class="col-sm-2">
		  <%= f.file_field :image %>
        </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink">
	    <div class="col-sm-2">
		  <%= f.text_field :description, placeholder: "description", class: "form-control" %>
	    </div>
	  </div>
	  <br /><br />
		  <div class="form-group">
		    <div class="col-sm-2">
			  <%= f.submit "Update!", class: "btn btn-pink" %>
			</div>
	      </div>
	  <br /><br />
		  <div class="form-group">
		    <div class="col-sm-2">
			  <%= link_to "Cancel Edit", foodiepictures_path, class: "btn btn-pink" %>
			</div>
	      </div>
	</form>
<% end %>

app/views/foodiepictures/index.html.erb
<ul>
	<% @foodiepictures.each do |p| %>
	<li>
		    <%= image_tag p.image.url, width: "150px", class: "img-thumbnail" %> 
		    <h1><%= link_to p.description, foodiepicture_path(p), class: "btn btn-pink" %></h1>
		    <% if current_user %>
		    <h class="btn btn-pink"><%= link_to "Uploaded by " + p.user.name, user_path(p.user_id) %></h>
		    <br /><br />
		    <div class="btn-group btn-block">
			    <%= link_to "Edit", edit_foodiepicture_path(p), class: "btn btn-pink" %>
			    <%= link_to "Delete", foodiepicture_path(p), method: :delete, data: { confirm: "Are you sure you want to delete #{p.description}?"}, class: "btn btn-pink" %>
			</div>
			
		    <% end %>
    </li>
    <% end %>

</ul>

app/views/foodiepictures/new.html.erb
<div class="newpic">
<h1>What did you eat today?</h1>
<%= form_for @foodiepicture do |f| %>
  <form class="form-horizontal" role="form">
	  <div class="form-group btn-pink">
	    <div class="col-sm-2">
		  <%= f.file_field :image, placeholder: "new food!", class: "form-control" %>
        </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink">
	    <div class="col-sm-2">
		  <%= f.text_field :description, placeholder: "description", class: "form-control" %>
	    </div>
	  </div>
	  <br /><br />
		  <div class="form-group">
		    <div class="col-sm-2">
			  <%= f.submit "Upload", class: "btn btn-pink" %>
			</div>
	      </div>
	  <br /><br />
		  <div class="form-group">
		    <div class="col-sm-2">
			  <%= link_to "Cancel Upload", foodiepictures_path, class: "btn btn-pink" %>
			</div>
	      </div>
	</form>
<% end %>

app/views/foodiepictures/show.html.erb
<div class="singlepic">
<%= image_tag @foodiepicture.image.url, width: "500pxs", class: "img-thumbnail" %>
    <br /> <br /> <br />

	<div class="btn-group btn-block">
		<h class="btn btn-pink"><%= @foodiepicture.description %></h>
	    <h class="btn btn-pink">by <%= link_to @foodiepicture.user.name, user_path(@foodiepicture.user) %></h>
	    <%= link_to "Edit", edit_foodiepicture_path, class: "btn btn-pink" %>
		<%= link_to "Delete", :foodiepicture, method: :delete, data: { confirm: "Are you sure you want to delete #{@foodiepicture.description}?"}, class: "btn btn-pink" %>
	</div>

<ul class="commentbox">
	<% @foodiepicture.comments.each do |c| %>
		<li>
			<% if current_user %>
				<%= c.user.name + ':' + c.comment %>
			<% end %>
		</li>
	<% end %>
</ul>

<!-- <div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
                <h3 class="panel-title">
                    Recent Comments</h3>
                <span class="label label-info">
                    78</span>
            </div>
            <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://www.jquery2dotnet.com/2013/10/google-style-login-page-desing-usign.html">
                                        Google Style Login Page Design Using Bootstrap</a>
                                    <div class="mic-info">
                                        By: <a href="#">Bhaumik Patel</a> on 2 Aug 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Awesome design
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://bootsnipp.com/BhaumikPatel/snippets/Obgj">Admin Panel Quick Shortcuts</a>
                                    <div class="mic-info">
                                        By: <a href="#">Bhaumik Patel</a> on 11 Nov 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                    euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <img src="http://placehold.it/80" class="img-circle img-responsive" alt="" /></div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <a href="http://bootsnipp.com/BhaumikPatel/snippets/4ldn">Cool Sign Up</a>
                                    <div class="mic-info">
                                        By: <a href="#">Bhaumik Patel</a> on 11 Nov 2013
                                    </div>
                                </div>
                                <div class="comment-text">
                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                                    euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim
                                </div>
                                <div class="action">
                                    <button type="button" class="btn btn-primary btn-xs" title="Edit">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button type="button" class="btn btn-success btn-xs" title="Approved">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" title="Delete">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <a href="#" class="btn btn-primary btn-sm btn-block" role="button"><span class="glyphicon glyphicon-refresh"></span> More</a>
            </div>
        </div>
    </div>
</div> -->


<div class="commentcontainer">
<%= form_for @comment_post, {url: comment_path(foodie_id: @id)} do |n| %>
    <%= n.text_field :comment, placeholder: "leave a comment..." %>
    <%= n.submit "Post comment!" %>
<% end %>
</div>

<% yield %>

<%# form_tag comment_path, :method=>'post' %>
	<%#= text_field_tag :comment, "leave a comment..." %>
	<%#= submit_tag "Submit" %>

<!-- <form action="/comment" method="post">
	<input type="text" name="comment" placeholder="leave a comment...">
	<input type="submit">
</form> -->

</div>

app/views/layouts/_login.html.erb
<%
=begin %>
<div class="info">
<%= form_for @user_login, {url: session_path} do |u| %>
  <%= u.text_field :name, placeholder: "username" %><br />
  <%= u.password_field :password, placeholder: "password" %>
<%= u.submit "Log In!" %>
<br />
<%= link_to "Back to the homepage!", foodiepictures_path %>
<% end %>
</div>
<%
=end%>

<div>
<%= form_for @user_login, {url: session_path} do |u| %>
	<form class="form-horizontal" role="form">
	  <div class="form-group btn-pink">
	    <div class="col-sm-12">
	     <%= u.text_field :name, placeholder: "username", class: "form-control btn-block" %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink">
	    <div class="col-sm-12">
	      <%= u.password_field :password, placeholder: "password", class: "form-control btn-block" %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group">
	    <div class="col-sm-12">
	      <%= u.submit "Log In!", class: "btn btn-pink btn-block" %>
	    </div>
	  </div>
	</form>
	<% end %>
</div>

app/views/layouts/_signup.html.erb
<div>
<%= form_for @user do |u| %>

	<form class="form-horizontal" role="form">
	  <div class="form-group btn-pink btn-block">
	    <div class="col-sm-12">
	     <%= u.text_field :name, placeholder: "create a username", class: "form-control" %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink btn-block">
	    <div class="col-sm-12">
	      <%= u.password_field :password, placeholder: "create a password", class: "form-control" %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink btn-block">
	    <div class="col-sm-12">
	      <%= u.password_field :password_confirmation, placeholder: "retype the password", class: "form-control" %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group btn-pink btn-block">
	    <div class="col-sm-12">
	      <%= u.file_field :image %>
	    </div>
	  </div>
	  <br /><br />
	  <div class="form-group">
	    <div class="col-sm-12">
	      <%= u.submit "Creat My Account!", class: "btn btn-pink btn-block" %>
	    </div>
	  </div>
	</form>
	<% end if !current_user %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<header>
	<link href='http://fonts.googleapis.com/css?family=Unkempt:700' rel='stylesheet' type='text/css'>
</header>
<head>
  <title>Foodiewall</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="heading">
		<h1>Foodie Wall</h1>

			<% if current_user %>

				<button class="btn btn-lg btn-pink btn-block">Welcome! 
					<% if current_user.image %>
						<img src="<%= current_user.image %>" id="userpic">
					<% end %>					
					<%= link_to current_user.name, user_path(current_user.id) %>
				</button>
				<%= link_to 'log out', session_path, class: "btn btn-lg btn-pink btn-block", method: :delete %></p>

			<% else %>

				<%= link_to 'log in', 'foodiepictures?form_type=login',
					class: "btn btn-lg btn-pink btn-block" %>

            <% end %>
	


			<%= link_to 'sign up', '/foodiepictures?form_type=signup',
				class: "btn btn-lg btn-pink btn-block" %>

			<%= link_to "Homepage", foodiepictures_path, class: "btn btn-lg btn-pink btn-block" %>
			<%= link_to "Upload new food!", new_foodiepicture_path, class: "btn btn-lg btn-pink btn-block" %>


			<% if @form_type == 'signup' %>
				<%= render 'layouts/signup' %>
			<% elsif @form_type == 'login' %>
				<%= render 'layouts/login' %>
			<% end %>

			<div class="notice"><strong><%= notice %></strong></div>

	
    </div>

   
    <%= yield %>



</body>
</html>

app/views/users/error.html.erb
<h1>You are not an authorized user for this picture!</h1>
<p><%= link_to "Sign In", new_session_path %> or <%= link_to "Sign Up" new_user_path %> to see more details!</p>
<%= link_to "Back to the homepage!", foodiepictures_path %>

app/views/users/show.html.erb
<div class="userpic">
	<ul>
		<% @foodiepictures.each do |p| %>
		    <li>
			    <%= image_tag p.image.url, width: "200px", class: "img-thumbnail" %> 
			    <h1><%= link_to p.description, foodiepicture_path(p), class: "btn btn-pink" %></h1>
			    <h class="btn btn-pink"><%= link_to "Uploaded by " + p.user.name, user_path(p.user_id) %></h>
			    <br /><br />
			    <div class="btn-group btn-block">
				    <%= link_to "Edit", edit_foodiepicture_path(p), class: "btn btn-pink" %>
				    <%= link_to "Delete", foodiepicture_path(p), method: :delete, data: { confirm: "Are you sure you want to delete #{p.description}?"}, class: "btn btn-pink" %>
				</div>
				<br />
		        <% end %>
	        </li>
	</ul>

	<ul class="commentbox">
		<% @user.comments.each do |c| %>
			<li>
				<% if current_user %>
					<%= c.user.name + ':' + c.comment %>
				<% end %>
			</li>
		<% end %>
	</ul>

	<div class="commentcontainer">
        <%= form_for @comment_post, {url: comment_path(userwall_id: @user.id)} do |i| %>
        <%= i.text_field :comment, placeholder: "leave a comment..." %>
        <%= i.submit "Post comment!" %>
        <% end %>
    </div>

</div>